name: Validate Envoy Config
description: Validate Envoy Proxy Configuration
inputs:
  path:
    description: 'Envoy Configuration file path'
    required: true
  image:
    description: 'Envoy Docker Image'
    required: true
  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  github_comment_opts:
    description: "github-comment options. Don't use --config option"
    required: false
  github_comment_config_path:
    description: |
      github-comment configuration file path.
      If "-" is specified, no configuration file path is specified.
    required: false
    default: ""
runs:
  using: composite
  steps:
    - run: docker pull ${{ inputs.image }}
      shell: bash

    - name: Validate Envoy Config
      run: |
        opts=""
        if [ "${{ inputs.github_comment_config_path }}" != "-" ]; then
          if [ "${{ inputs.github_comment_config_path }}" = "" ]; then
            opts="--config ${{ github.action_path }}/src/github-comment.yml"
          else
            opts="--config ${{ inputs.github_comment_config_path }}"
          fi
        fi
        opts="$opts ${{ inputs.github_comment_opts }}"
        github-comment exec \
          $opts -- \
          docker run --rm --entrypoint envoy \
          -v "$PWD:/workspace" -w /workspace ${{ inputs.image }} \
          --mode validate -c ${{ inputs.path }}
        exit 0
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
