---
name: test-actions
on:
  pull_request:
    branches: [main]
    paths:
      - examples/invalid-envoy.yaml
      - .github/workflows/test-actions.yaml
      - action.yaml
      - src/**
jobs:
  default:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
        with:
          aqua_version: v2.38.0

      - run: github-comment hide
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: ./
        with:
          path: examples/invalid-envoy.yaml
          image: envoyproxy/envoy-alpine:v1.20.1
