---
name: test-actions
on:
  pull_request:
    branches: [main]
    paths:
      - examples/invalid-envoy.yaml
      - .github/workflows/test-actions.yaml
      - action.yaml
      - src/**
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - uses: aquaproj/aqua-installer@a39f721a15ed34ccbc85706e6e8ae8572c9ca9c6 # v1.2.0
        with:
          aqua_version: v1.12.1

      - run: github-comment hide
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: ./
        with:
          path: examples/invalid-envoy.yaml
          image: envoyproxy/envoy-alpine:v1.20.1
