---
name: test-actions
on:
  pull_request:
    branches: [main]
    paths:
      - examples/invalid-envoy.yaml
      - .github/workflows/test-actions.yaml
      - action.yaml
      - src/**
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aquaproj/aqua-installer@v0.6.0
        with:
          aqua_version: v0.10.1

      - run: github-comment hide
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: ./
        with:
          path: examples/invalid-envoy.yaml
          image: envoyproxy/envoy-alpine:v1.20.1
